on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - name: Conventional commit check
        uses: oknozor/cocogitto-action@main

      - run: |
          cog --help